const recipeDetails = {
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: true,
  cheap: false,
  veryPopular: true,
  sustainable: false,
  lowFodmap: false,
  weightWatcherSmartPoints: 15,
  gaps: 'no',
  preparationMinutes: 5,
  cookingMinutes: 0,
  aggregateLikes: 689,
  healthScore: 64,
  creditsText: 'Jen West',
  sourceName: 'Pink When',
  pricePerServing: 206.79,
  extendedIngredients: [
    {
      id: 1009040,
      aisle: 'Produce',
      image: 'bananas.jpg',
      consistency: 'SOLID',
      name: 'banana',
      nameClean: 'mashed banana',
      original: '¼ cup mashed banana',
      originalName: 'mashed banana',
      amount: 0.25,
      unit: 'cup',
      meta: ['mashed'],
      measures: {
        us: { amount: 0.25, unitShort: 'cups', unitLong: 'cups' },
        metric: { amount: 56.25, unitShort: 'g', unitLong: 'grams' },
      },
    },
    {
      id: 10018617,
      aisle: 'Baking',
      image: 'graham-crackers.jpg',
      consistency: 'SOLID',
      name: 'graham cracker crumbs',
      nameClean: 'graham cracker crumbs',
      original: '2 tbsp graham cracker crumbs',
      originalName: 'graham cracker crumbs',
      amount: 2.0,
      unit: 'tbsp',
      meta: [],
      measures: {
        us: { amount: 2.0, unitShort: 'Tbsps', unitLong: 'Tbsps' },
        metric: { amount: 2.0, unitShort: 'Tbsps', unitLong: 'Tbsps' },
      },
    },
    {
      id: 16223,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'soy-milk.jpg',
      consistency: 'LIQUID',
      name: 'soy milk',
      nameClean: 'soymilk',
      original: '1 cup soy milk',
      originalName: 'soy milk',
      amount: 1.0,
      unit: 'cup',
      meta: [],
      measures: {
        us: { amount: 1.0, unitShort: 'cup', unitLong: 'cup' },
        metric: { amount: 236.0, unitShort: 'ml', unitLong: 'milliliters' },
      },
    },
    {
      id: 9316,
      aisle: 'Produce',
      image: 'strawberries.png',
      consistency: 'SOLID',
      name: 'strawberries',
      nameClean: 'strawberries',
      original: '½ cup strawberries',
      originalName: 'strawberries',
      amount: 0.5,
      unit: 'cup',
      meta: [],
      measures: {
        us: { amount: 0.5, unitShort: 'cups', unitLong: 'cups' },
        metric: { amount: 72.0, unitShort: 'g', unitLong: 'grams' },
      },
    },
    {
      id: 1119,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'vanilla-yogurt.png',
      consistency: 'LIQUID',
      name: 'vanilla yogurt',
      nameClean: 'vanilla yogurt',
      original: '1 container vanilla yogurt',
      originalName: 'vanilla yogurt',
      amount: 1.0,
      unit: 'container',
      meta: [],
      measures: {
        us: { amount: 1.0, unitShort: 'container', unitLong: 'container' },
        metric: {
          amount: 1.0,
          unitShort: 'container',
          unitLong: 'container',
        },
      },
    },
  ],
  id: 715497,
  title: 'Berry Banana Breakfast Smoothie',
  readyInMinutes: 5,
  servings: 1,
  sourceUrl: 'http://www.pinkwhen.com/berry-banana-breakfast-smoothie/',
  image: 'https://spoonacular.com/recipeImages/715497-312x231.jpg',
  imageType: 'jpg',
  summary:
    'If you want to add more <b>lacto ovo vegetarian</b> recipes to your recipe box, Berry Banana Breakfast Smoothie might be a recipe you should try. One portion of this dish contains about <b>21g of protein</b>, <b>10g of fat</b>, and a total of <b>457 calories</b>. This recipe serves 1 and costs $2.07 per serving. 689 people have tried and liked this recipe. It works well as a rather inexpensive breakfast. A mixture of banana, graham cracker crumbs, vanilla yogurt, and a handful of other ingredients are all it takes to make this recipe so yummy. From preparation to the plate, this recipe takes roughly <b>5 minutes</b>. It is brought to you by Pink When. Overall, this recipe earns a <b>super spoonacular score of 99%</b>. Similar recipes include <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1364145">Berry Banana Breakfast Smoothie</a>, <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1405583">Berry Banana Breakfast Smoothie</a>, and <a href="https://spoonacular.com/recipes/berry-banana-breakfast-smoothie-1601311">Berry Banana Breakfast Smoothie</a>.',
  cuisines: [],
  dishTypes: ['morning meal', 'brunch', 'beverage', 'breakfast', 'drink'],
  diets: ['lacto ovo vegetarian'],
  occasions: [],
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Take some yogurt in your favorite flavor and add 1 container to your blender.',
          ingredients: [
            {
              id: 1116,
              name: 'yogurt',
              localizedName: 'yogurt',
              image: 'plain-yogurt.jpg',
            },
          ],
          equipment: [
            {
              id: 404726,
              name: 'blender',
              localizedName: 'blender',
              image: 'blender.png',
            },
          ],
        },
        {
          number: 2,
          step: 'Add in the berries, banana, and soy milk and blend. Top your glass with a few graham cracker crumbs and serve.',
          ingredients: [
            {
              id: 10018617,
              name: 'graham cracker crumbs',
              localizedName: 'graham cracker crumbs',
              image: 'graham-crackers.jpg',
            },
            {
              id: 16223,
              name: 'soymilk',
              localizedName: 'soymilk',
              image: 'soy-milk.jpg',
            },
            {
              id: 1009054,
              name: 'berries',
              localizedName: 'berries',
              image: 'berries-mixed.jpg',
            },
            {
              id: 9040,
              name: 'banana',
              localizedName: 'banana',
              image: 'bananas.jpg',
            },
          ],
          equipment: [],
        },
      ],
    },
  ],
  spoonacularSourceUrl:
    'https://spoonacular.com/berry-banana-breakfast-smoothie-715497',
  usedIngredientCount: 0,
  missedIngredientCount: 5,
  missedIngredients: [
    {
      id: 1009040,
      amount: 0.25,
      unit: 'cup',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Produce',
      name: 'banana',
      original: '¼ cup mashed banana',
      originalName: 'mashed banana',
      meta: ['mashed'],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/bananas.jpg',
    },
    {
      id: 10018617,
      amount: 2.0,
      unit: 'tbsp',
      unitLong: 'tablespoons',
      unitShort: 'Tbsp',
      aisle: 'Baking',
      name: 'graham cracker crumbs',
      original: '2 tbsp graham cracker crumbs',
      originalName: 'graham cracker crumbs',
      meta: [],
      image:
        'https://spoonacular.com/cdn/ingredients_100x100/graham-crackers.jpg',
    },
    {
      id: 16223,
      amount: 1.0,
      unit: 'cup',
      unitLong: 'cup',
      unitShort: 'cup',
      aisle: 'Milk, Eggs, Other Dairy',
      name: 'soy milk',
      original: '1 cup soy milk',
      originalName: 'soy milk',
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/soy-milk.jpg',
    },
    {
      id: 9316,
      amount: 0.5,
      unit: 'cup',
      unitLong: 'cups',
      unitShort: 'cup',
      aisle: 'Produce',
      name: 'strawberries',
      original: '½ cup strawberries',
      originalName: 'strawberries',
      meta: [],
      image: 'https://spoonacular.com/cdn/ingredients_100x100/strawberries.png',
    },
    {
      id: 1119,
      amount: 1.0,
      unit: 'container',
      unitLong: 'container',
      unitShort: 'container',
      aisle: 'Milk, Eggs, Other Dairy',
      name: 'vanilla yogurt',
      original: '1 container vanilla yogurt',
      originalName: 'vanilla yogurt',
      meta: [],
      image:
        'https://spoonacular.com/cdn/ingredients_100x100/vanilla-yogurt.png',
    },
  ],
  likes: 0,
  usedIngredients: [],
  unusedIngredients: [],
};
export default recipeDetails;
